# Generated by Django 4.2.4 on 2023-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomanager",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
