# Generated by Django 4.2.5 on 2023-09-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("greta", "0002_portfoliomanager_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                ("buy_action", models.BooleanField()),
                ("num_shares", models.IntegerField()),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "portfolio_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="greta.portfoliomanager",
                    ),
                ),
            ],
        ),
    ]
