# Generated by Django 4.2.5 on 2023-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greta", "0004_portfoliomanager_cash_basis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliomanager",
            name="cash_basis",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
